/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'selector',
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./contexts/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./types/**/*.{js,ts,jsx,tsx,mdx}",
    "./styles/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          500: '#3b82f6',
          600: '#2563eb',
        },
        secondary: {
          50: '#f0fdfa',
          500: '#10b981',
          600: '#059669',
        }
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, var(--tw-gradient-stops))',
      }
    },
  },
  safelist: [
    // Common Tailwind classes to prevent purging
    { pattern: /bg-(primary|secondary)-\d+/ },
    { pattern: /text-(primary|secondary)-\d+/ },
    { pattern: /border-(primary|secondary)-\d+/ },
    { pattern: /rounded-/ },
    { pattern: /p-\d+/ },
    { pattern: /m-\d+/ },
    { pattern: /flex/ },
    { pattern: /grid/ },
    { pattern: /grid-cols-/ },
    { pattern: /gap-/ },
    { pattern: /w-\d+/ },
    { pattern: /h-\d+/ },
    { pattern: /shadow-/ },
    { pattern: /transition-/ },
    { pattern: /duration-/ },
    { pattern: /ease-/ },
    { pattern: /animate-/ },
    { pattern: /scale-/ },
    { pattern: /opacity-/ },
    { pattern: /transform/ },
    { pattern: /hover:/ },
    { pattern: /focus:/ },
    { pattern: /dark:/ },
    { pattern: /backdrop-/ },
    { pattern: /blur-/ },
    { pattern: /gradient-/ },
    { pattern: /from-/ },
    { pattern: /to-/ },
    { pattern: /via-/ },
    { pattern: /font-/ },
    { pattern: /text-/ },
    { pattern: /leading-/ },
    { pattern: /tracking-/ },
    { pattern: /uppercase/ },
    { pattern: /lowercase/ },
    { pattern: /capitalize/ },
    { pattern: /italic/ },
    { pattern: /underline/ },
    { pattern: /line-through/ },
    { pattern: /placeholder-/ },
    { pattern: /cursor-/ },
    { pattern: /pointer-events-/ },
    { pattern: /resize-/ },
    { pattern: /overflow-/ },
    { pattern: /scroll-/ },
    { pattern: /align-/ },
    { pattern: /justify-/ },
    { pattern: /items-/ },
    { pattern: /self-/ },
    { pattern: /order-/ },
    { pattern: /flex-/ },
    { pattern: /grow-/ },
    { pattern: /shrink-/ },
    { pattern: /table-/ },
    { pattern: /border-/ },
    { pattern: /divide-/ },
    { pattern: /ring-/ },
    { pattern: /outline-/ },
    { pattern: /appearance-/ },
    { pattern: /box-/ },
    { pattern: /display-/ },
    { pattern: /position-/ },
    { pattern: /float-/ },
    { pattern: /clear-/ },
    { pattern: /z-/ },
    { pattern: /top-/ },
    { pattern: /right-/ },
    { pattern: /bottom-/ },
    { pattern: /left-/ },
    { pattern: /inset-/ },
    { pattern: /inset-x-/ },
    { pattern: /inset-y-/ },
  ],
  plugins: [],
}